scripts = {
        "flood_history":lambda: f"var num={input('Amount of tabs: ')};done=false;x=window.location.href;for (var i=1; i<=num; i++){{history.pushState(0, 0, i==num?x:i.toString());if(i==num){{done=true}}}}",
        "play_mp3":lambda: f"javascript:(function(){{var audio=new Audio('{input('mp3 url:')}');audio.play();var imgs=document.getElementsByTagName('img');for(var i=0;i<imgs.length;i++){{imgs[i].src='https://i.kym-cdn.com/entries/icons/original/000/043/027/metalpipefalling.jpg';}}}})();",
    "alert":lambda: f"alert('{input('message: ')}')",
    "background_image":lambda: f"document.body.style.backgroundImage = \"url('{input('body background image url: ')}')\";",
    "add_script_tag":lambda: f"document.body.appendChild(Object.assign(document.createElement('script'),{{src:'{input('script link: ')}'}}));",
    "3d_webpage": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/3Dwebpage.js'}));",
    "among_us": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/AmongUs.js'}));",
    "asteroids": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/Astoids.js'}));",
    "blur": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/Blur.js'}));",
    "bubble_text": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/BubbleText.js'}));",
    "color_drop": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/ColorDrop.js'}));",
    "colorful": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/Colorful.js'}));",
    "corrupt": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/Corrupt.js'}));",
    "custom_matrix": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/CustomMatrix.js'}));",
    "domii": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/DOMII.js'}));",
    "fake_chrome_update": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/FakeChromeUpdate.js'}));",
    "flashlight": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/Flashlight.js'}));",
    "freeze": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/Freeze.js'}));",
    "glitch": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/Glitch.js'}));",
    "gold": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/Gold.js'}));",
    "grayscale": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/Grayscale.js'}));",
    "harlem_shake": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/HarlemShake.js'}));",
    "high_contrast": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/HighContrastMode.js'}));",
    "high_pitched_noise": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/HighPitchedNoisePlayer.js'}));",
    "image_flip": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/ImageFlip.js'}));",
    "image_fly": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/ImageFly.js'}));",
    "insanity": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/Insanity.js'}));",
    "jellify": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/Jellify.js'}));",
    "let_it_snow": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/LetItSnow.js'}));",
    "matrix": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/Matrix.js'}));",
    "metal_pipe": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/MetalPipe.js'}));",
    "mouse_sword": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/MouseSword.js'}));",
    "mouse_trail": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/MouseTrail.js'}));",
    "no_click": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/NoClick.js'}));",
    "print_every_key": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/PrintEveryKey.js'}));",
    "rainbow_drugs": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/RainbowDrugs.js'}));",
    "random_tilt": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/RandomTilt.js'}));",
    "shrek": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/Shrek.js'}));",
    "shrek_v2": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/ShrekV2.js'}));",
    "dark_mode": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/SimpleDarkMode.js'}));",
    "sniper": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/Sniper.js'}));",
    "star_wars": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/StarWarsIntro.js'}));",
    "tab_spinner": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/TabSpinner.js'}));",
    "time_display": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/TimeDisplay.js'}));",
    "uwu": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/UwU.js'}));",
    "virus": lambda: "document.body.appendChild(Object.assign(document.createElement('script'),{src:'https://cdn.jsdelivr.net/gh/DevBubba/Bookmarklets@main/Screen/Virus.js'}));"
}
